# Generated by Django 6.0 on 2026-02-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated.')),
                ('latitude', models.FloatField(help_text='The last known latitude of the user.')),
                ('longitude', models.FloatField(help_text='The last known longitude of the user.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
