"""
Django settings for vita project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


def env(key, default: str | None = None) -> str:
    val = os.getenv(key, default)
    if val is None and default is None:
        raise KeyError(
            f"Environment variable '{key}' not found and no default value provided."
        )
    if val:
        return val

    return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = env("ALLOWED_HOSTS", "localhost,127.0.0.1,.fly.dev").split(",")

CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS", "https://*.fly.dev").split(",")

CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SECURE = True

# SECURE_HSTS_SECONDS = 3600  # TODO: Update to larger value in production

# SECURE_SSL_REDIRECT = True

# SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django_extensions",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django_bootstrap5",
    "django_htmx",
    "django_tasks",
    "django_tasks.backends.database",
    "core",
    "tasks",
    "health",
    "journal",
    "social",
    "notifications",
    "api",
    "assistant",
]

ASGI_APPLICATION = "vita.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "core.middleware.SuperuserRequiredMiddleware",
]

if DEBUG:
    INSTALLED_APPS += [
        "django_browser_reload",
    ]
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]


ROOT_URLCONF = "vita.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "assistant.context_processors.assistant_widget",
            ],
        },
    },
]

WSGI_APPLICATION = "vita.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_PATH = Path(os.getenv("DB_PATH", BASE_DIR / "db.sqlite3"))

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_PATH,
        "OPTIONS": {
            "transaction_mode": "IMMEDIATE",
        },
    }
}


def _enable_wal_mode(sender, connection, **kwargs):
    if connection.vendor == "sqlite":
        cursor = connection.cursor()
        cursor.execute("PRAGMA journal_mode=WAL;")
        cursor.execute("PRAGMA busy_timeout=5000;")


from django.db.backends.signals import connection_created  # noqa: E402

connection_created.connect(_enable_wal_mode)

# Tasks
TASKS = {"default": {"BACKEND": "django_tasks.backends.database.DatabaseBackend"}}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# Email

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
RESEND_SMTP_PORT = 587
RESEND_SMTP_USERNAME = "resend"
RESEND_SMTP_HOST = "smtp.resend.com"
SELF_EMAIL = env("SELF_EMAIL")

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

VITA_API_KEY = env("VITA_API_KEY")

# Assistant / LLM
ASSISTANT_LLM_PROVIDER = env("ASSISTANT_LLM_PROVIDER", "openai").lower()
ASSISTANT_OPENAI_MODEL = env("ASSISTANT_OPENAI_MODEL", "gpt-4o-mini")
OPENAI_API_KEY = env("OPENAI_API_KEY", "")
ASSISTANT_SYSTEM_PROMPT_FILE = env(
    "ASSISTANT_SYSTEM_PROMPT_FILE", "assistant/system_prompt.txt"
)
ASSISTANT_SYSTEM_PROMPT = env("ASSISTANT_SYSTEM_PROMPT", "").strip()
ASSISTANT_SYSTEM_PROMPT_DEFAULT = (
    "You are Vita's assistant. Keep replies concise and actionable."
)
ASSISTANT_VOICE_SYSTEM_PROMPT_FILE = env(
    "ASSISTANT_VOICE_SYSTEM_PROMPT_FILE", "assistant/system_prompt_voice.txt"
)
ASSISTANT_VOICE_SYSTEM_PROMPT = env("ASSISTANT_VOICE_SYSTEM_PROMPT", "").strip()
ASSISTANT_VOICE_SYSTEM_PROMPT_DEFAULT = (
    "You are Vita's phone assistant. Reply in concise, natural spoken sentences."
)

ELEVEN_LABS_API_KEY = env("ELEVEN_LABS_API_KEY")
ELEVEN_LABS_VOICE_ID = env("ELEVEN_LABS_VOICE_ID")

# Web Push (VAPID)
WEBPUSH_VAPID_PUBLIC_KEY = env("WEBPUSH_VAPID_PUBLIC_KEY", "")
WEBPUSH_VAPID_PRIVATE_KEY = env("WEBPUSH_VAPID_PRIVATE_KEY", "")
WEBPUSH_VAPID_EMAIL = env("WEBPUSH_VAPID_EMAIL", "")

# Provide dev-friendly VAPID keys if missing
if not WEBPUSH_VAPID_PUBLIC_KEY or not WEBPUSH_VAPID_PRIVATE_KEY:
    try:
        import base64
        from cryptography.hazmat.primitives.asymmetric import ec

        vapid_file = BASE_DIR / ".vapid.json"
        if vapid_file.exists():
            import json

            keys = json.loads(vapid_file.read_text())
            WEBPUSH_VAPID_PUBLIC_KEY = (
                WEBPUSH_VAPID_PUBLIC_KEY or keys.get("public") or ""
            )
            WEBPUSH_VAPID_PRIVATE_KEY = (
                WEBPUSH_VAPID_PRIVATE_KEY or keys.get("private") or ""
            )
        elif DEBUG:
            # Generate ephemeral dev keys
            priv = ec.generate_private_key(ec.SECP256R1())
            priv_num = priv.private_numbers().private_value
            pub_nums = priv.public_key().public_numbers()
            x = pub_nums.x.to_bytes(32, "big")
            y = pub_nums.y.to_bytes(32, "big")
            uncompressed = b"\x04" + x + y
            WEBPUSH_VAPID_PUBLIC_KEY = (
                base64.urlsafe_b64encode(uncompressed).decode("ascii").rstrip("=")
            )
            WEBPUSH_VAPID_PRIVATE_KEY = (
                base64.urlsafe_b64encode(priv_num.to_bytes(32, "big"))
                .decode("ascii")
                .rstrip("=")
            )
            # Persist to file for consistent dev sessions
            try:
                import json

                vapid_file.write_text(
                    json.dumps(
                        {
                            "public": WEBPUSH_VAPID_PUBLIC_KEY,
                            "private": WEBPUSH_VAPID_PRIVATE_KEY,
                        }
                    )
                )
            except Exception:
                pass
    except Exception:
        # Leave keys empty if generation fails
        pass

# Twilio

FROM_PHONE_NUMBER = env("FROM_PHONE_NUMBER")
TO_PHONE_NUMBER = env("TO_PHONE_NUMBER")
TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN")
TWILIO_VALIDATE_SIGNATURES = (
    env("TWILIO_VALIDATE_SIGNATURES", "True").strip().lower() == "true"
)
TWILIO_CONVERSATION_RELAY_WS_URL = env("TWILIO_CONVERSATION_RELAY_WS_URL", "").strip()
TWILIO_CONVERSATION_RELAY_WELCOME_GREETING = env(
    "TWILIO_CONVERSATION_RELAY_WELCOME_GREETING",
    "Hi, this is Vita. How can I help?",
).strip()
TWILIO_CONVERSATION_RELAY_LANGUAGE = env(
    "TWILIO_CONVERSATION_RELAY_LANGUAGE", "en-US"
).strip()
TWILIO_CONVERSATION_RELAY_ASSISTANT_USER_ID = env(
    "TWILIO_CONVERSATION_RELAY_ASSISTANT_USER_ID", ""
).strip()
TWILIO_CONVERSATION_RELAY_APPROVED_CALL_TTL_SECONDS = int(
    env("TWILIO_CONVERSATION_RELAY_APPROVED_CALL_TTL_SECONDS", "1800")
)
