# Generated by Django 6.0 on 2025-12-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_routine_routinestep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of integers representing days of the week (0=Sunday, 6=Saturday).",
                null=True,
            ),
        ),
    ]
