# Generated by Django 6.0 on 2025-12-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_alter_task_options_remove_task_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To do"),
                    ("in_progress", "In progress"),
                    ("blocked", "Blocked"),
                    ("cancelled", "Cancelled"),
                    ("done", "Done"),
                ],
                default="todo",
                help_text="Current workflow state.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                default="New task", help_text="Short task title.", max_length=255
            ),
        ),
    ]
