# Generated by Django 6.0 on 2025-12-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_contact_strength_alter_contacttouchpoint_contact_and_more"),
        ("tasks", "0010_alter_task_status_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="related_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Contact associated with this task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_tasks",
                to="social.contact",
            ),
        ),
    ]
