# Generated by Django 6.0 on 2025-12-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_task_related_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status_last_changed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the status last changed.", null=True
            ),
        ),
    ]
