# Generated by Django 6.0 on 2025-12-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_task_status_last_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="routinestep",
            name="is_stackable",
            field=models.BooleanField(
                default=True,
                help_text="Whether multiple uncompleted tasks of this step can exist simultaneously.",
            ),
        ),
    ]
