# Generated by Django 6.0 on 2025-12-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_routinestep_is_stackable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routinestep",
            name="is_stackable",
            field=models.BooleanField(
                default=False,
                help_text="Whether multiple uncompleted tasks of this step can exist simultaneously.",
            ),
        ),
    ]
