# Generated by Django 6.0 on 2026-01-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0014_alter_routinestep_is_stackable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="anchor_time",
            field=models.TimeField(
                blank=True,
                help_text="When to add the task to the board (e.g., 08:00).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To do"),
                    ("in_progress", "In progress"),
                    ("on_deck", "On Deck"),
                    ("blocked", "Blocked"),
                    ("missed", "Missed"),
                    ("cancelled", "Cancelled"),
                    ("done", "Done"),
                ],
                default="todo",
                help_text="Current workflow state.",
                max_length=20,
            ),
        ),
    ]
