# Generated by Django 6.0 on 2026-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0015_alter_routine_anchor_time_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To do"),
                    ("in_progress", "In progress"),
                    ("on_deck", "On deck"),
                    ("blocked", "Blocked"),
                    ("missed", "Missed"),
                    ("cancelled", "Cancelled"),
                    ("done", "Done"),
                ],
                default="todo",
                help_text="Current workflow state.",
                max_length=20,
            ),
        ),
    ]
