# Generated by Django 6.0 on 2026-02-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_isawayfromhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAwayTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the away period.')),
                ('end_date', models.DateField(help_text='End date of the away period.')),
                ('title', models.CharField(help_text='Title for the away period.', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='IsAwayFromHome',
        ),
    ]
