# Generated by Django 6.0 on 2026-02-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_routinestep_typical_completion_percentiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Optional details about this tag.'),
        ),
    ]
