# Generated by Django 6.0 on 2025-12-09 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
