# Generated by Django 6.0 on 2025-12-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_contact_check_in_frequency_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacttouchpoint",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                max_length=100,
            ),
        ),
    ]
