# Generated by Django 6.0 on 2025-12-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_contacttouchpoint_sentiment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                (
                    "slug",
                    models.SlugField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="social.contact"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
