# Generated by Django 6.0 on 2025-12-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="nickname",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
