# Generated by Django 6.0 on 2025-12-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0006_rename_name_contact_first_name_contact_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="strength",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="contacttouchpoint",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="touchpoints",
                to="social.contact",
            ),
        ),
        migrations.AlterField(
            model_name="contacttouchpoint",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                default="positive",
                max_length=100,
            ),
        ),
    ]
