# Generated by Django 6.0 on 2025-12-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_contact_strength_alter_contacttouchpoint_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contacttouchpoint",
            name="sentiment",
        ),
    ]
