# Generated by Django 6.0 on 2026-02-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_remove_contacttouchpoint_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_ever_contacted',
            field=models.BooleanField(default=False, help_text='Indicates if this contact has ever been contacted.'),
        ),
    ]
