# Generated by Django 6.0 on 2026-02-03 05:08

from django.db import migrations


def set_ever_contacted(apps, schema_editor):
    Contact = apps.get_model("social", "Contact")
    Touchpoint = apps.get_model("social", "ContactTouchpoint")

    # Get all contact IDs that have at least one touchpoint
    contacted_ids = Touchpoint.objects.values_list("contact_id", flat=True).distinct()
    # Update is_ever_contacted to True for these contacts
    Contact.objects.filter(slug__in=contacted_ids).update(is_ever_contacted=True)


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0009_contact_is_ever_contacted"),
    ]

    operations = [
        migrations.RunPython(set_ever_contacted),
    ]
