# Generated by Django 6.0 on 2026-02-03 05:20

from django.db import migrations
from django.db.models import Exists, OuterRef


def backfill_contact_touchpoints(apps, schema_editor):
    Contact = apps.get_model("social", "Contact")
    ContactTouchpoint = apps.get_model("social", "ContactTouchpoint")

    missing_contacts = (
        Contact.objects.exclude(last_contacted_at__isnull=True)
        .annotate(
            has_match=Exists(
                ContactTouchpoint.objects.filter(
                    contact_id=OuterRef("pk"),
                    date=OuterRef("last_contacted_at"),
                )
            )
        )
        .filter(has_match=False)
    )

    touchpoints_to_create = []
    for contact in missing_contacts.iterator():
        channel = contact.preferred_channel or "in_person"
        touchpoints_to_create.append(
            ContactTouchpoint(
                contact_id=contact.pk,
                date=contact.last_contacted_at,
                channel=channel,
                notes="Backfilled from last_contacted_at.",
            )
        )

    if touchpoints_to_create:
        ContactTouchpoint.objects.bulk_create(touchpoints_to_create, batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0010_BackfillEverContacted"),
    ]

    operations = [
        migrations.RunPython(backfill_contact_touchpoints, migrations.RunPython.noop),
    ]
