# Generated by Django 6.0 on 2025-12-24 00:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("cardio", "Cardio"),
                            ("mobility", "Mobility"),
                            ("other", "Other"),
                        ],
                        default="strength",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="health_exer_slug_f87cb3_idx"),
                    models.Index(
                        fields=["category"], name="health_exer_categor_fd9a4f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                (
                    "value_lb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Body weight in pounds (lb).",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "logged_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the weight was measured.",
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-logged_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["logged_at"], name="health_weig_logged__7ed547_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeightGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                (
                    "target_lb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target body weight in pounds (lb).",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("start_date", models.DateField(help_text="When the goal starts.")),
                (
                    "target_date",
                    models.DateField(help_text="When you aim to reach the target."),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_active", "target_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "target_date"],
                        name="health_weig_is_acti_c29bc7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkoutRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="health_work_slug_fff419_idx"),
                    models.Index(
                        fields=["is_active"], name="health_work_is_acti_a5b413_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("duration_min", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "workout_routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="health.workoutroutine",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Order within the session."),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_items",
                        to="health.exercise",
                    ),
                ),
                (
                    "workout_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="health.workoutsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SessionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                (
                    "set_number",
                    models.PositiveIntegerField(
                        help_text="Set order within the exercise."
                    ),
                ),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "load_lb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual load in pounds (lb).",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rpe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rate of Perceived Exertion (1-10).",
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "session_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="health.sessionexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["set_number", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session_exercise", "set_number"),
                        name="unique_session_set_order",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Order within the routine."),
                ),
                ("target_sets", models.PositiveIntegerField(default=3)),
                ("target_reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_load_lb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target load in pounds (lb).",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "target_duration_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_items",
                        to="health.exercise",
                    ),
                ),
                (
                    "workout_routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="health.workoutroutine",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workout_routine", "order"), name="unique_routine_order"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["performed_at"], name="health_work_perform_508a36_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionexercise",
            constraint=models.UniqueConstraint(
                fields=("workout_session", "order"), name="unique_session_order"
            ),
        ),
    ]
