# Generated by Django 6.0 on 2025-12-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="exercise",
            name="health_exer_slug_f87cb3_idx",
        ),
        migrations.RemoveIndex(
            model_name="exercise",
            name="health_exer_categor_fd9a4f_idx",
        ),
        migrations.RemoveConstraint(
            model_name="routineexercise",
            name="unique_routine_order",
        ),
        migrations.RemoveConstraint(
            model_name="sessionexercise",
            name="unique_session_order",
        ),
        migrations.RemoveConstraint(
            model_name="sessionset",
            name="unique_session_set_order",
        ),
        migrations.RemoveIndex(
            model_name="weightentry",
            name="health_weig_logged__7ed547_idx",
        ),
        migrations.DeleteModel(
            name="WeightEntry",
        ),
        migrations.RemoveIndex(
            model_name="weightgoal",
            name="health_weig_is_acti_c29bc7_idx",
        ),
        migrations.DeleteModel(
            name="WeightGoal",
        ),
        migrations.RemoveIndex(
            model_name="workoutroutine",
            name="health_work_slug_fff419_idx",
        ),
        migrations.RemoveIndex(
            model_name="workoutroutine",
            name="health_work_is_acti_a5b413_idx",
        ),
        migrations.RemoveIndex(
            model_name="workoutsession",
            name="health_work_perform_508a36_idx",
        ),
        migrations.RemoveField(
            model_name="sessionexercise",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="sessionexercise",
            name="workout_session",
        ),
        migrations.RemoveField(
            model_name="sessionset",
            name="session_exercise",
        ),
        migrations.RemoveField(
            model_name="workoutsession",
            name="workout_routine",
        ),
        migrations.DeleteModel(
            name="RoutineExercise",
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
        migrations.DeleteModel(
            name="SessionExercise",
        ),
        migrations.DeleteModel(
            name="SessionSet",
        ),
        migrations.DeleteModel(
            name="WorkoutRoutine",
        ),
        migrations.DeleteModel(
            name="WorkoutSession",
        ),
    ]
